version: "3"
services:
  hadoop:
    image: 5200710/hadoop:3.2.1-pseudo
    container_name: hadoop-pseudo
    volumes:
      - ./data:/data
    ports:
      - 9870:9870
      - 8088:8088
      - 8042:8042
      - 8020:8020